[package]
name = "subarraysum_native"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "subarraysum_native"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.34.0"
